export const filterOptions = [
  { value: 'all', name: 'Все партнеры' },
  { value: 'popular', name: 'Популярные' },
  { value: 'markets', name: 'Супермаркеты' },
  { value: 'cafe', name: 'Кафе и рестораны' },
  { value: 'taxi', name: 'Такси' },
  { value: 'beauty', name: 'Красота' },
  { value: 'electronics', name: 'Электроника и бытовая техника' },
  { value: 'zoo', name: 'Зоотовары' },
  { value: 'cinema', name: 'Кино и театр' },
  { value: 'connect', name: 'Связь и интерент' },
  { value: 'lottery', name: 'Лотереи' },
  { value: 'sport', name: 'Спорт' },
  { value: 'trip', name: 'Путешествия' },
  { value: 'health', name: 'Здоровье' },
  { value: 'insurance', name: 'Страхование' },
  { value: 'immovables', name: 'Недвижимость' },
  { value: 'entertainment', name: 'Развлечения' },
  { value: 'education', name: 'Образование' },
]

